version: "3"

services:
  influxdb:
    image: influxdb:1.8
    restart: always
    # Uncomment below you want the DB exposed for use elsewhere
    # ports:
    #   - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=speedtest
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_INSTALL_PLUGINS=dalvany-image-panel
    depends_on:
      - influxdb
  speedtest:
    image: jmacalinao/speedtest-influx
    restart: always
    # Uncomment below if you need to set these variables
    # environment:
    #   - SPEEDTEST_INTERVAL=
    #   - SPEEDTEST_SERVER=
    depends_on:
      - influxdb

volumes:
  influxdb: